language: node_js
node_js: "8.12.0"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    packages:
      - build-essential

install:
  - yarn install
  - npm i -g truffle@beta
  - npm i -g ganache-cli

script:
  - ganache-cli > /dev/null &
  - sleep 5
  - truffle test
