- name: Template nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true

- name: Make sure forwarding is allowed on selinux systems
  command: "setsebool -P httpd_can_network_connect on"
  ignore_errors: true
  become: true

- name: Copy over ssl keys
  copy:
    src: "eth-{{item}}"
    dest: "/etc/nginx/{{item}}"
  with_items:
    - fullchain.pem
    - privkey.pem
  when: not dai

- name: Copy over ssl keys
  copy:
    src: "dai-{{item}}"
    dest: "/etc/nginx/{{item}}"
  with_items:
    - fullchain.pem
    - privkey.pem
  when: dai

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  become: true
