# Installs the latest stable ipfs node and sets it to run on boot

- name: download and unpack ipfs tar
  unarchive:
    remote_src: yes
    src: "{{ipfs_tar_url}}"
    dest: "/tmp/"
  become: true

- name: Copy bin to final location
  copy:
    remote_src: yes
    src: "/tmp/go-ipfs/ipfs"
    dest: "/usr/bin/ipfs"
    mode: "0755"
  become: true

- name: Run ipfs init
  shell: "ipfs init"
  become: true
  ignore_errors: true

- name: Template ipfs service file
  template:
    src: ipfs.service.j2
    dest: /etc/systemd/system/ipfs.service
  become: true

- name: Set ipfs to run on startup
  systemd:
    daemon_reload: yes
    name: ipfs
    state: restarted
    enabled: yes
  become: true

- name: Wait for Quick crashes
  pause:
    seconds: 30

- name: Check if ipfs is running
  command: systemctl status ipfs
  ignore_errors: yes
  changed_when: false
  register: service_ipfs_status

- name: Report status of ipfs
  fail:
    msg: |
      Service ipfs is not running.
      Output of `systemctl status ipfs`:
      {{ service_ipfs_status.stdout }}
      {{ service_ipfs_status.stderr }}
  when: service_ipfs_status is failed

- name: Open ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{item[0]}}"
    jump: ACCEPT
    ip_version: "{{item[1]}}"
    ctstate: NEW
  become: true
  with_nested:
    - "{{ipfs_ports}}"
    - ["ipv4", "ipv6"]

- name: save iptables rules
  shell: "service {{item}} save"
  become: true
  with_items:
    - iptables
    - ip6tables
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'

- name: save iptables rules
  shell: "{{item}}"
  become: true
  with_items:
    - "iptables-save > /etc/iptables/rules.v4"
    - "ip6tables-save > /etc/iptables/rules.v6"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'